### ISSUE TITLE
Melfest, weird interaction with the pull-down menu on iOS

### ISSUE THREAD

**Issue by fredrik-jarnbrost** [stagecast/bug-report#156]
**Describe the bug**
There is a weird interaction with the pull-down menu on iOS, see video linked below

**Screenshots**
https://drive.google.com/open?id=1o2Q46jN_S0A9tRve4Ayq4HYE8vK5IfKF

**Comment by peffis** [comment]
I don't think it's weird. What happens when you pull the notification thing down is that the app state changes to passive (just like if you would switch to a different app). Then when you release it the app becomes active again and this will (in our case) trigger the app to reload in order to always present the accurate information. One could argue that you should not see that it is updating the screen...but this is all expected behaviour and according to the current plan. We can create a new issue that says something like "entering active state should not let the screen flicker" as a future improvement, but this is not going to change now, so closing.

**Comment by fredrik-jarnbrost** [comment]
@peffis oh ok! That makes sense. But at 0:25 in the video the scrolled-to moment seem to change from color to flash, is that the same thing?
